name:                otus-proto
version:             0.1.0.0
author:              "dark-flames"
maintainer:          "github@dark-flames.dev"
copyright:           "2025 dark-flames"

extra-source-files:
- README.md

description:         prototype of Otus project

dependencies:
- base >= 4.20.1.0 && < 4.20.2.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wredundant-constraints

default-extensions:
- MultiParamTypeClasses
- StandaloneDeriving
- FlexibleInstances
- ScopedTypeVariables
- TupleSections
- FlexibleContexts
- LambdaCase
- PatternSynonyms
- ViewPatterns

library:
  source-dirs: src